import {
  TrendingUp,
  RefreshCcw,
  CalendarCheck,
  Percent,
  Banknote,
} from "lucide-react";
import { getAuthContext } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { getRevenueData } from "@/lib/services/revenue";
import { PageHeader } from "@/components/dashboard/page-header";
import { StatCard } from "@/components/dashboard/stat-card";
import { MonthlyRevenueChart } from "@/components/charts/monthly-revenue-chart";
import { RevenueSourceChart } from "@/components/charts/revenue-source-chart";
import { DownloadReportButton } from "@/components/dashboard/revenue/download-report-button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { formatCurrency } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function RevenuePage() {
  const ctx = await getAuthContext();
  const supabase = await createClient();
  const { summary, monthly } = await getRevenueData(supabase, ctx!.clinic, 6);

  const thisMonth = monthly[monthly.length - 1]?.estimatedRevenue ?? 0;

  return (
    <>
      <PageHeader
        title="Revenue Impact & ROI"
        description="The business value generated by your AI receptionist."
      >
        <DownloadReportButton clinicName={ctx!.clinic.name} summary={summary} monthly={monthly} />
      </PageHeader>

      <div className="rounded-md bg-primary/5 px-4 py-3 text-sm text-primary">
        All figures below are <strong>Estimated Revenue</strong> — projections based on your
        average appointment value, not collected payments.
      </div>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">
        <StatCard
          label="Est. Revenue Generated"
          value={formatCurrency(summary.estimatedRevenueGenerated)}
          icon={TrendingUp}
          hint={`${summary.appointmentsBooked} appointments booked`}
        />
        <StatCard
          label="Est. Revenue Recovered"
          value={formatCurrency(summary.estimatedRevenueRecovered)}
          icon={RefreshCcw}
          accent="emerald"
          hint={`${summary.recoveredAppointments} recovered appointments`}
        />
        <StatCard
          label="Est. Revenue This Month"
          value={formatCurrency(thisMonth)}
          icon={Banknote}
          accent="amber"
        />
        <StatCard
          label="Recovered Appointments"
          value={summary.recoveredAppointments}
          icon={CalendarCheck}
          accent="emerald"
        />
        <StatCard
          label="Recovery Conversion Rate"
          value={`${summary.recoveryConversionRate}%`}
          icon={Percent}
          accent="amber"
          hint="Recovered ÷ missed calls"
        />
        <StatCard
          label="Avg Appointment Value"
          value={formatCurrency(summary.averageAppointmentValue)}
          icon={Banknote}
        />
      </div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-5">
        <Card className="lg:col-span-3">
          <CardHeader>
            <CardTitle>Estimated revenue by month</CardTitle>
          </CardHeader>
          <CardContent>
            <MonthlyRevenueChart data={monthly} />
          </CardContent>
        </Card>
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>Estimated revenue by source</CardTitle>
          </CardHeader>
          <CardContent>
            <RevenueSourceChart data={summary.bySource} />
          </CardContent>
        </Card>
      </div>
    </>
  );
}
